name: Make release

on:
  workflow_dispatch:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  make-release:
    uses: BQN-UY/CI-CD/.github/workflows/scala-api-make-release.yml@v2
    secrets: inherit
