name: Publish and deploy

on:
  push:
    branches: [develop, "hotfix/**", "release/**"]

jobs:
  publish-and-deploy:
    uses: BQN-UY/CI-CD/.github/workflows/scala-api-publish-deploy.yml@v2
    secrets: inherit
    # with:
    #   java-version: "21"
    #   sistema: "mi-servicio"   # default = vars.SISTEMA o nombre del repo
