name: Start hotfix

on:
  workflow_dispatch:
    inputs:
      description:
        description: Descripción corta del bug (ej. fix-null-parser)
        required: true

jobs:
  start-hotfix:
    uses: BQN-UY/CI-CD/.github/workflows/scala-api-start-hotfix.yml@v2
    secrets: inherit
    with:
      description: ${{ inputs.description }}
