name: Start release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Tipo de bump de versión
        required: true
        default: minor
        type: choice
        options: [major, minor, patch]

jobs:
  start-release:
    uses: BQN-UY/CI-CD/.github/workflows/scala-api-start-release.yml@v2
    secrets: inherit
    with:
      bump: ${{ inputs.bump }}
