# .github/actions/jenkins/app-dispatcher.yml
name: 'Ejecutar Job en Jenkins'
description: 'Ejecuta un job específico en Jenkins.'
inputs:
  deploy_ip:
    description: 'IP del servidor de despliegue'
    required: true
  deploy_port:
    description: 'Puerto SSH del servidor de despliegue'
    required: true
  deploy_user:
    description: 'Usuario SSH del servidor de despliegue'
    required: true
  jenkins_url:
    description: 'URL de Jenkins'
    required: true
  jenkins_job_name: 
    description: 'Nombre del job de Jenkins a ejecutar'
    required: true
  jenkins_user:
    description: 'Usuario que ejecutó el evento'
    required: true
  sistema:
    description: 'Nombre del sistema'
    required: true
  version:
    description: 'Versión'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Job in Jenkins
      shell: bash
      run: |
        # Curl para el crumbs
        crumb=$(curl -u "${{ inputs.jenkins_user }}:${{ secrets.JENKINS_TOKEN }}" -s '${{ inputs.jenkins_url }}/crumbIssuer/api/json')
        # Curl para ejecutar
        curl -u "${{ inputs.jenkins_user }}:${{ secrets.JENKINS_TOKEN }}" -H "$crumb" -X POST '${{ inputs.jenkins_url }}/${{ inputs.jenkins_job_name }}/buildWithParameters?SISTEMA=${{ inputs.sistema }}&VERSION=${{ inputs.version }}'