name: deploy-war

on:
  workflow_call:
      name:
        type: string
        description: name
        required: true
    secrets:
      DEPLOY_USER:
        required: true
      DEPLOY_KEY:
        required: true
      DEPLOY_IP:
        required: true
      DEPLOY_PORT:
        required: true
      JENKINS_URL:
        required: true
      JENKINS_DEPLOY_JOB:
        required: true
      JENKINS_USER:
        required: true
      JENKINS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: "${{inputs.name}}"
          path: "./"

      - name: Get current version
        run: |
          versionString=$(awk '/ThisBuild \/ version := /{print $NF}' version.sbt)
          echo "VERSION=`echo ${versionString:1:-1}`" >> $GITHUB_ENV

      - name: Executing deloy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            # Curl para el crumbs
            crumb=$(curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" -s '${{ secrets.JENKINS_URL }}/crumbIssuer/api/json')
            # Curl para ejecutar
            curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" -H "$crumb" -X POST '${{ secrets.JENKINS_URL }}/${{ secrets.JENKINS_DEPLOY_JOB }}/buildWithParameters?SISTEMA=${{inputs.name}}&VERSION=${{env.VERSION}}'