name: release-drafter

on:
  workflow_call:
    secrets:
      SYSADMIN_PAT:
        required: true

jobs:
  release-drafter:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}
