name: release-drafter

on:
  workflow_call:
    secrets:
      SYSADMIN_PAT:
        required: true

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: version.sbt
          branch: main
          token: ${{ secrets.SYSADMIN_PAT }}

      - run: |
          versionString=$(awk '/ThisBuild \/ version := /{print $NF}' version.sbt)
          echo "VERSION=`echo ${versionString:1:-1} | sed 's/-SNAPSHOT//g'`" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          commitish: main
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}
