name: release-drafter

on:
  workflow_call:
    secrets:
      SYSADMIN_PAT:
        required: true

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout version.sbt
        uses: Bhacaz/checkout-files
        with:
          files: version.sbt
          token: ${{ secrets.SYSADMIN_PAT }}

      - name: Get current version
        run: |
          versionString=$(awk '/ThisBuild \/ version := /{print $NF}' version.sbt)
          echo "VERSION=`echo ${versionString:1:-1} | sed 's/-SNAPSHOT//g'`" >> $GITHUB_ENV

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          commitish: main
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}
