name: scala-deploy-web

on:
  workflow_call:
    inputs:
      jdk-version:
        required: false
        description: 'jdk version'
        type: string
        default: '8'
      environment:
        type: string
        description: environment
        required: true
      name:
        type: string
        description: name
        required: true
    secrets:
      SYSADMIN_PAT:
        required: true
      NEXUS_USER:
        required: true
      NEXUS_PASSWORD:
        required: true
      DEPLOY_KEY:
        required: true
      DEPLOY_IP:
        required: true
      DEPLOY_PORT:
        required: true


jobs:
  testing:
    if: inputs.environment == 'testing'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Checkout / Setup JDK / sbt-cache
        uses: BQN-UY/action_checkout_jdk_sbt-cache@main
        with:
          token: ${{ secrets.SYSADMIN_PAT }}
          jdk-version: ${{ inputs.jdk-version }}

      - name: Build war
        run: sbt package

      - name: Get current version
        run: |
          versionString=$(awk '/ThisBuild \/ version := /{print $NF}' version.sbt)
          echo "VERSION=`echo ${versionString:1:-1}`" >> $GITHUB_ENV

      - name: Storage Testing War
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avz --delete'
          options: ''
          ssh_options: '-p ${{secrets.DEPLOY_PORT}}'
          src: 'target/${{inputs.name}}.war'
          dest: 'github@${{secrets.DEPLOY_IP}}:/opt/publisher/testing/${{inputs.name}}-${{env.VERSION}}.war'
#          dest: 'github@${{secrets.DEPLOY_IP}}:/opt/publisher/testing/${{inputs.name}}/${{inputs.name}}-${{env.VERSION}}.war'

#      TODO: Entender si es con esto o disparar algo de jenkins
#      - name: Deploy Testing Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.SYSADMIN_PAT }}
#          repository: BQN-UY/CI-CD
#          event-type: deployer-auto
#          client-payload: '{"repo": "spa", "version": "${{ env.VERSION }}", "environment": "TESTING", "installation": "DEFAULT"}'



