name: scala-ci

on:
  workflow_call:
    secrets:
      SYSADMIN_PAT:
        required: true

jobs:
  labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Label the PR action
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}

  u-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            ~/.cache/coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

      - name: Run Unit Tests
        run: sbt unitTests

      - name: Report Unit Tests
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: u-tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/*UnitTest.xml

  merge-update:
    if: startsWith(github.event.pull_request.head.ref, 'update') &&  github.actor == 'bqn-sysadmin'
    needs: [ labeler, u-tests ]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Merge PR with Minor Update
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: squash
