name: scala-publish-snapshot-lib

on:
  workflow_call:

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            ~/.cache/coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

      - name: Publish Snapshot
        run: sbt publish

