name: scala-publish-snapshot-lib

on:
  workflow_call:
    inputs:
      jdk-version:
        required: false
        description: 'jdk version'
        type: string
        default: '8'

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout / Setup JDK / sbt-cache
        uses: ./.github/actions/checkout_jdk_sbt-cache
        with:
          token: ${{ secrets.SYSADMIN_PAT }}
          jdk-version: ${{ inputs.jdk-version }}

      - name: Publish Snapshot
        run: sbt publish

