name: scala-publish-snapshot-lib

on:
  workflow_call:

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout / Setup JDK 8 / sbt-cache
        uses: BQN-UY/action-checkout-jdk8-sbt-cache@main
        with:
          token: ${{ secrets.SYSADMIN_PAT }}
          fetch-depth: '0'

      - name: Publish Snapshot
        run: sbt publish

