name: scala-deploy-web

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment
        required: true
      artifact:
        type: string
        description: artifact
        required: true
    secrets:
      SYSADMIN_PAT:
        required: true
      DEPLOY_KEY:
        required: true
      DEPLOY_IP:
        required: true
      DEPLOY_PORT:
        required: true


jobs:
  ci:
    uses: BQN-UY/CI-CD/.github/workflows/scala-ci.yml@main
    secrets:
      SYSADMIN_PAT: ${{ secrets.SYSADMIN_PAT }}

  testing:
    needs: [ci]
    if: inputs.environment == 'testing'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            ~/.cache/coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

      - name: Build war
        run: sbt package

      - name: Get current version
        run: |
          versionString=$(awk '/ThisBuild \/ version := /{print $NF}' version.sbt)
          echo "VERSION=`echo ${versionString:1:-1}`" >> $GITHUB_ENV

      - name: Storage Testing War
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avz --delete'
          options: ''
          ssh_options: '-p ${{secrets.DEPLOY_PORT}}'
          src: 'target/${{inputs.artifact}}.war'
          dest: 'github@${{secrets.DEPLOY_IP}}:/opt/publisher/testing/${{inputs.artifact}}-${{env.VERSION}}.war'

#      TODO: Entender si es con esto o disparar algo de jenkins
#      - name: Deploy Testing Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.SYSADMIN_PAT }}
#          repository: BQN-UY/CI-CD
#          event-type: deployer-auto
#          client-payload: '{"repo": "spa", "version": "${{ env.VERSION }}", "environment": "TESTING", "installation": "DEFAULT"}'



