name: scala-ci

on:
  workflow_call:
    inputs:
      jdk-version:
        required: false
        description: 'jdk version'
        type: string
        default: '8'
      run-utest:
        required: false
        description: 'Run or skip unit test'
        type: string
        default: 'true'
    secrets:
      SYSADMIN_PAT:
        required: true
      NEXUS_USER:
        required: true
      NEXUS_PASSWORD:
        required: true

jobs:
  labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Label the PR action
        uses: TimonVS/pr-labeler-action@v5
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}

  u-tests:
    if: "(${{ inputs.run-utest == 'true' }} && !(contains(github.event.head_commit.message, 'ci:') || contains(github.event.head_commit.message, '(ci)')))"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TZ: America/Montevideo
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Checkout / Setup JDK / sbt-cache
        uses: BQN-UY/action_checkout_jdk_sbt-cache@main
        with:
          token: ${{ secrets.SYSADMIN_PAT }}
          jdk-version: ${{ inputs.jdk-version }}

      - name: Run Unit Tests
        run: sbt unitTests

      - name: Report Unit Tests
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: u-tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/*UnitTest.xml

  merge-update:
    if: startsWith(github.event.pull_request.head.ref, 'update') &&  github.actor == 'bqn-sysadmin'
    needs: [ labeler, u-tests ]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Merge PR with Minor Update
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.SYSADMIN_PAT }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: squash
