# .github/actions/store-artifact/action.yml
name: 'Almacenar Artifacto Remoto'
description: 'Transfiere un artifacto a un servidor remoto usando rsync.'
inputs:
  publisher_path:
    description: 'Ruta en el servidor remoto donde se almacenará el artifacto'
    required: true
  artifact_path:
    description: 'Ruta local completa al artifacto a transferir (ej: target/mi-aplicacion.war)'
    required: true
  artifact_name:
    description: 'Nombre base del artifacto (sin extensión, para la ruta remota)'
    required: true
  version:
    description: 'Versión del artifacto'
    required: true
runs:
  using: "composite"
  steps:
    - name: Storage Artifact
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        flags: '-avz --delete'
        options: ''
        ssh_options: '-p ${{ secrets.DEPLOY_PORT }}'
        src: '${{ inputs.artifact_path }}'
        dest: '${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:${{ inputs.publisher_path }}/${{ inputs.artifact_name }}/versiones/${{ inputs.artifact_name }}-${{ inputs.version }}/${{ inputs.artifact_path == '' ? '' : inputs.artifact_path.split("/")[-1] }}'